### ISSUE TITLE
Ability to set language or other options of Captcha

### ISSUE THREAD

**Issue by riasvdv** [barrelstrength/craft-sprout-forms-google-recaptcha#1]
Is it possible to expose the options for the captcha through a config file or settings page? Like theme, language, ...

Thanks!

**Comment by ademers** [comment]
I have a bilingual EN & FR site and it would be nice to show a French reCaptcha to FR site visitors. I'm assuming this could be done by setting language code(s) in a config/settings page as mentioned above. https://developers.google.com/recaptcha/docs/language

**Comment by BenParizek** [comment]
@riasvdv @ademers I've just released v1.1.0 which adds support for several additional options:

- Added support for Invisible reCAPTCHA v2
- Added Invisible reCAPTCHA settings for Language, Theme, and Badge Type including an 'Inline Text' option to display a line of text terms instead of a badge
- Added Checkbox reCAPTCHA settings for Language, Theme, and Size
- Added support for using reCAPTCHA when displaying multiple forms on a page 

It doesn't appear there is any way to dynamically show a list of supported languages so I've hard coded a lists that matches the languages currently available per the documentation. If the list is added to in the future, we'll have to manually add support for them so just open a ticket or pull request if you run into that scenario.
